- name: Next Pages
  uses: anorcle/next-pages@v1.0
- name: Commit and push changes
  run: |
    git config --global user.name "anorcle"
    git config --global user.email "next-pages@anorcle.com"
    git add -A
    git commit -m "New Build"
    git push
